[project]
name = "tg-br-video"
version = "0.1.0"
description = "Telegram bot for BR video examination"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "loguru>=0.7.3",
]
